import{a as P,S as $,i as n}from"./assets/vendor-g8RIeo89.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const x="50492024-422e121587c507d29de78ae86",C="https://pixabay.com/api/",f=async(e,r=1,s=15)=>{try{return(await P.get(C,{params:{key:x,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s}})).data}catch(a){throw console.error("Error fetching images:",a),new Error("Could not fetch images")}};let l;const g=e=>{const r=document.querySelector(".gallery"),s=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:c,views:v,comments:q,downloads:E})=>`
      <li class="gallery-item">
        <a href="${t}">
          <img src="${a}" alt="${o}" loading="lazy" />
        </a>
        <div class="image-info">
          <span><b>Likes:</b> ${c}</span>
          <span><b>Views:</b> ${v}</span>
          <span><b>Comments:</b> ${q}</span>
          <span><b>Downloads:</b> ${E}</span>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",s),l&&l.refresh()},M=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},p=()=>{const e=document.querySelector(".loader");e.classList.remove("hidden"),e.classList.add("visible")},L=()=>{const e=document.querySelector(".loader");e.classList.remove("visible"),e.classList.add("hidden")},b=()=>{l&&l.destroy(),l=new $(".gallery a",{captionsData:"alt",captionDelay:250})},w=document.querySelector(".form"),O=w.querySelector('input[name="search-text"]'),h=document.querySelector(".load-more");document.querySelector(".loader");let m="",i=1;const d=15;let u=0;const A=()=>{i=1,u=0},S=()=>{h.classList.remove("hidden")},y=()=>{h.classList.add("hidden")};w.addEventListener("submit",async e=>{e.preventDefault();const r=O.value.trim();if(r===""){n.error({title:"Error",message:"Please enter a search query."});return}M(),y(),A(),m=r,p();try{const s=await f(m,i,d);u=s.totalHits,s.hits.length===0?n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):(g(s.hits),b(),d*i<u?S():(y(),n.info({title:"",message:"We're sorry, but you've reached the end of search results."})))}catch{n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{L()}});h.addEventListener("click",async()=>{i+=1,p(),y();try{const e=await f(m,i,d);g(e.hits),b();const r=document.querySelector(".gallery-item");if(r){const{height:s}=r.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}d*i<u?S():(y(),n.info({title:"",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{L()}});
//# sourceMappingURL=index.js.map
